package 
        visual;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.MenuElement;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicMenuBarUI;

public class FormPrincipal extends javax.swing.JFrame {


    public FormPrincipal() {
        initComponents();
        configurarMenuBar();
               
        setResizable(false);   
        
}
    
    private void configurarMenuBar() {
        
        barraMenu.setUI(new BasicMenuBarUI() {

            @Override
            public void paint(Graphics g, JComponent c) {
                g.setColor(new Color(4, 52, 68)); // Cor #043444
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }
         });
        
         MenuElement[] menus = barraMenu.getSubElements();
            
         for (MenuElement menuElement : menus) {

           JMenu menu = (JMenu) menuElement.getComponent();
           changeComponentColors(menu);
           menu.setOpaque(true);

           MenuElement[] menuElements = menu.getSubElements();

           for (MenuElement popupMenuElement : menuElements) {

               JPopupMenu popupMenu = (JPopupMenu) popupMenuElement.getComponent();
               popupMenu.setBorder(null);

               MenuElement[] menuItens = popupMenuElement.getSubElements();

               for (MenuElement menuItemElement : menuItens) {

                   JMenuItem menuItem = (JMenuItem) menuItemElement.getComponent();
                   changeComponentColors2(menuItem);
                   menuItem.setOpaque(true);

               }
           }
       }
        
        
    }
    
    private void changeComponentColors(Component comp) {       
        comp.setBackground(new Color(4, 52, 68));
        comp.setForeground(new Color(255, 255, 255));
    }
    
    private void changeComponentColors2(Component comp) {       
        comp.setBackground(new Color(9, 92, 120));
        comp.setForeground(new Color(255, 255, 255));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuAeroporto = new javax.swing.JMenuItem();
        menuAeronave = new javax.swing.JMenuItem();
        menuPiloto = new javax.swing.JMenuItem();
        menuPassageiro = new javax.swing.JMenuItem();
        menuVoo = new javax.swing.JMenuItem();
        menuPassagem = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenu();
        menuAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cadastro");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(676, 450));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/WhatsApp Image 2023-06-26 at 07.23.31.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 676, 420);

        barraMenu.setBorder(null);
        barraMenu.setBorderPainted(false);

        menuCadastro.setBackground(new java.awt.Color(4, 52, 68));
        menuCadastro.setBorder(null);
        menuCadastro.setForeground(new java.awt.Color(188, 148, 132));
        menuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Icons-menuPrincipal/IconsBarraMenu/icons8-cadastro-30 (1).png"))); // NOI18N
        menuCadastro.setText("Cadastro");
        menuCadastro.setFocusPainted(true);
        menuCadastro.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        menuCadastro.setIconTextGap(5);
        menuCadastro.setOpaque(true);

        menuAeroporto.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        menuAeroporto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Icons-menuPrincipal/Icons-BarraCadastro/icons8-aeroporto-25 .png"))); // NOI18N
        menuAeroporto.setText("Aeroporto");
        menuAeroporto.setBorder(null);
        menuAeroporto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAeroportoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuAeroporto);

        menuAeronave.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        menuAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Icons-menuPrincipal/Icons-BarraCadastro/icons8-avião-25.png"))); // NOI18N
        menuAeronave.setText("Aeronave");
        menuAeronave.setBorder(null);
        menuAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAeronaveActionPerformed(evt);
            }
        });
        menuCadastro.add(menuAeronave);

        menuPiloto.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        menuPiloto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Icons-menuPrincipal/Icons-BarraCadastro/icons8-chapéu-de-piloto-25.png"))); // NOI18N
        menuPiloto.setText("Piloto");
        menuPiloto.setBorder(null);
        menuPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPilotoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuPiloto);

        menuPassageiro.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        menuPassageiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Icons-menuPrincipal/Icons-BarraCadastro/icons8-passageiro-25.png"))); // NOI18N
        menuPassageiro.setText("Passageiro");
        menuPassageiro.setBorder(null);
        menuPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPassageiroActionPerformed(evt);
            }
        });
        menuCadastro.add(menuPassageiro);

        menuVoo.setText("Voo");
        menuVoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVooActionPerformed(evt);
            }
        });
        menuCadastro.add(menuVoo);

        menuPassagem.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        menuPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Icons-menuPrincipal/Icons-BarraCadastro/icons8-cartão-de-embarque-25.png"))); // NOI18N
        menuPassagem.setText("Passagem");
        menuPassagem.setBorder(null);
        menuPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPassagemActionPerformed(evt);
            }
        });
        menuCadastro.add(menuPassagem);

        barraMenu.add(menuCadastro);

        menuVenda.setText("Venda");
        menuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendaActionPerformed(evt);
            }
        });
        barraMenu.add(menuVenda);

        menuAjuda.setBackground(new java.awt.Color(4, 52, 68));
        menuAjuda.setBorder(null);
        menuAjuda.setForeground(new java.awt.Color(188, 148, 132));
        menuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Icons-menuPrincipal/IconsBarraMenu/icons8-ajuda-30 (1).png"))); // NOI18N
        menuAjuda.setText("Ajuda");
        menuAjuda.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        menuAjuda.setIconTextGap(5);
        menuAjuda.setMargin(new java.awt.Insets(0, 0, 0, 100));

        menuSobre.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        menuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Icons-menuPrincipal/Icons-BarraAjuda/icons8-informação-25.png"))); // NOI18N
        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuSobre);

        barraMenu.add(menuAjuda);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAeroportoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAeroportoActionPerformed
        // TODO add your handling code here:
        FormAeroporto form  = new FormAeroporto(this,true);
        //this: chama a partir deste form
        // true: Modal: sobre o form principal e não deixa acessa-lo
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        // não deixa fechar o form pelo x
        form.setLocationRelativeTo(null); // centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true); //mostra o form
    }//GEN-LAST:event_menuAeroportoActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null,"Sistema de Cadastro\nDireitos reservado\nVersão 1.0");
    }//GEN-LAST:event_menuSobreActionPerformed

    private void menuAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAeronaveActionPerformed
         // TODO add your handling code here:
        FormAeronave form  = new FormAeronave(this,true);
        //this: chama a partir deste form
        // true: Modal: sobre o form principal e não deixa acessa-lo
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        // não deixa fechar o form pelo x
        form.setLocationRelativeTo(null); // centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true); //mostra o form
    }//GEN-LAST:event_menuAeronaveActionPerformed

    private void menuPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPilotoActionPerformed
        // TODO add your handling code here:
        FormPiloto form  = new FormPiloto(this,true);
        //this: chama a partir deste form
        // true: Modal: sobre o form principal e não deixa acessa-lo
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        // não deixa fechar o form pelo x
        form.setLocationRelativeTo(null); // centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true); //mostra o form
    }//GEN-LAST:event_menuPilotoActionPerformed

    private void menuPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPassageiroActionPerformed
         // TODO add your handling code here:
        FormPassageiro form  = new FormPassageiro(this,true);
        //this: chama a partir deste form
        // true: Modal: sobre o form principal e não deixa acessa-lo
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        // não deixa fechar o form pelo x
        form.setLocationRelativeTo(null); // centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true); //mostra o form
    }//GEN-LAST:event_menuPassageiroActionPerformed

    private void menuPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPassagemActionPerformed
        FormPassagem form  = new FormPassagem(this,true);
        //this: chama a partir deste form
        // true: Modal: sobre o form principal e não deixa acessa-lo
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        // não deixa fechar o form pelo x
        form.setLocationRelativeTo(null); // centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true); //mostra o form
    }//GEN-LAST:event_menuPassagemActionPerformed

    private void menuVooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVooActionPerformed
        FormVoo form  = new FormVoo(this,true);
        //this: chama a partir deste form
        // true: Modal: sobre o form principal e não deixa acessa-lo
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        // não deixa fechar o form pelo x
        form.setLocationRelativeTo(null); // centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true); //mostra o form
    }//GEN-LAST:event_menuVooActionPerformed

    private void menuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendaActionPerformed
         FormVenda form  = new FormVenda(this,true);
        //this: chama a partir deste form
        // true: Modal: sobre o form principal e não deixa acessa-lo
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        // não deixa fechar o form pelo x
        form.setLocationRelativeTo(null); // centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true); //mostra o form
    }//GEN-LAST:event_menuVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new FormPrincipal().setVisible(true);
               FormPrincipal form = new FormPrincipal();
               form.setLocationRelativeTo(null);//janela no centro
               form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem menuAeronave;
    private javax.swing.JMenuItem menuAeroporto;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuPassageiro;
    private javax.swing.JMenuItem menuPassagem;
    private javax.swing.JMenuItem menuPiloto;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JMenu menuVenda;
    private javax.swing.JMenuItem menuVoo;
    // End of variables declaration//GEN-END:variables
}
